- scripts/uefi-run.sh
Very minor nits with the `uefi-run.sh` script.
- Check the input and do not run if no arg is given
- `mkfs.msdos` should just be a symlink to `mkfs.fat` (Gentoo users that do not enable the `copmat` USE flag for `dosfstools` don't get `mkfs.msdos`)
> Fixup nits in the uefi-run script

- Cargo.lock
- Cargo.toml
- src/error.rs
- src/vmx.rs
Check cpuid feature information to ensure that the CPU supports VMX
early in Vmx::enable.
Run the `qemu` command with `-cpu host,-vmx` and you should get an error
like the following before hitting an invalid opcode.
```
ERROR: Failed to enable vmx: NotSupported
```
Run with `cpu host,+vmx` and everything should be fine and dandy.
If I'm honest, I'm not entirely sure how useful this is. It is highly unlikely
someone would pick this up and try to use it on a CPU that didn't support
vmx.
> Check the cpuid Feature Information for VMX bit

- src/device.rs
- src/efialloc.rs
- src/error.rs
- src/main.rs
- src/memory.rs
- src/vm.rs
- src/vmcs.rs
- src/vmx.rs
- Cleanup `vmxon_region` on `vmxon` instruction error
- Fix some warnings
- Remove some unused imports
- Fix some unused results
- Fix unreachable code warning
- Remove an unneeded `unsafe` block
- Fix some unused value warnings.
> Minor cleanups

- Makefile
Use cargo's `manifest-path` argument instead of the `cd <foo> && cargo ...`.
> build: use manifest-path instead of cd

- Makefile
Some options in qemu may contain colons in the value e.g.
-serial file:foo.txt
We need to escape these colons in the make goals before evaluating.
Fixes: #32
> build: Escape colons in qemu extra arguments

- mythril_core/src/device/mod.rs
- mythril_core/src/error.rs
- Add checks to `DeviceMap::register_device` for detecting existing mappings by another device in the map.
- Add `InvalidDevice` to `mythril_core::error::Error`.
fixes #27
> Add DeviceMap device conflict detection.

- mythril_core/src/apic.rs
- mythril_core/src/error.rs
- mythril_core/src/lib.rs
- mythril_core/src/rsdp.rs
- mythril_core/src/vcpu.rs
Add `LocalApic` with basic x2apic support. Added the initial structure and methods for the `LocalApic`.
Related to: #26
> Initial groundwork for apic support

- Makefile
- mythril_core/src/acpi/madt.rs
- mythril_core/src/acpi/mod.rs
- mythril_core/src/acpi/rsdp.rs
- mythril_core/src/acpi/rsdt.rs
- mythril_core/src/apic.rs
- mythril_core/src/lib.rs
- mythril_core/src/rsdp.rs
- mythril_multiboot2/src/main.rs
Add support for the Root System Descriptor Table in the `rsdt` module in
`mythril_core`.
Signed-off-by: Dan Robertson <daniel.robertson@starlab.io>
> core: add support for the RSDT

- .mythril_githooks/pre-commit
- Makefile
Currently this just installs git hooks. Really I just want to ensure I don't keep winding up in these situations where I've done a bunch of work but it turns out there were formatting issues that are very annoying to rebase.
I feel like I've seen some idiomatic name for the make target to install git hooks and such, but I can't find an example now.
> Add 'dev-init' make target

- mythril_core/src/device/acpi.rs
- mythril_core/src/lib.rs
- mythril_core/src/logger.rs
- mythril_core/src/time.rs
- mythril_core/src/tsc.rs
- mythril_multiboot2/src/main.rs
This is the first step to having time tick in the guest context. Once we have a way to really inject interrupts into the guests, the timer will be extended to contain the IRQ the timer should trigger in the guest.
> Add basic global time source

- mythril_core/src/acpi/hpet.rs
- mythril_core/src/acpi/mod.rs
- mythril_multiboot2/src/main.rs
This PR adds support for parsing the ACPI HPET entry structure.
Fixes #53
> Add HPET ACPI struct.

- mythril_core/src/acpi/madt.rs
- mythril_core/src/error.rs
- mythril_core/src/ioapic.rs
- mythril_core/src/lib.rs
- mythril_multiboot2/src/main.rs
Add basic I/O APIC support with the ioapic module in mythril_core.
Fixes: #26
> Add basic I/O APIC support.

- mythril_core/src/acpi/rsdp.rs
- mythril_core/src/acpi/rsdt.rs
- mythril_multiboot2/src/services.rs
- scripts/grub.cfg
Fixes: https://github.com/mythril-hypervisor/mythril/issues/54
> closes acpi: add support for the xsdt

- mythril_core/src/device/mod.rs
- mythril_core/src/memory.rs
- format GustPhysAddr integer as hexidecimal
- format HostPhysAddr integer as hexidecimal
- format MemWriteRequest data bytes as hexidecimal
```
[   5.383615] MYTHRIL-INFO: local apic read of addr = GuestPhysAddr(0xfee00280) (len=0x4)
[   5.386908] MYTHRIL-INFO: local apic write of addr = GuestPhysAddr(0xfee00370) (data=MemWriteRequest { data: [00, 00, 00, fe] })
```
> core: improve readability of fmt::Debug output

- mythril_core/src/logger.rs
- Add VgaWriter struct to handle text output to the VGA.
- Add vga_logger module containing VGA text mode helper functions.
- mirror console output to VGA.
fixes #43
> VGA console output implementation.

- Cargo.lock
- mythril_multiboot2/Cargo.toml
- mythril_multiboot2/src/services.rs
Updates multiboot2 from 0.8.2 to 0.9.0 and checks the RSDP checksum before using it.
Fixes #72
> multiboot: Check RSDP checksum

- mythril/src/acpi/fadt.rs
- mythril/src/acpi/mod.rs
This PR adds parsing support for the FADT ACPI table. Since the FADT can be variable length, I've made all the members `Option<T>` and they are only `Some` up until the underlying ACPI table ends.
closes #52
> acpi: Add FADT parsing support

- mythril/Cargo.lock
- mythril/Cargo.toml
- mythril/build.rs
- mythril/linker.ld
- mythril/src/boot.S
- mythril/src/kmain.rs
- mythril/src/lib.rs
- mythril/src/multiboot.rs
- mythril/src/multiboot2_header.S
- mythril/src/multiboot_header.S
Unfortunately, we can't use this with direct grub boot as that only supports 32bit multiboot images. Still, there may be some value in using this for network booting, etc.
> Add support for legacy multiboot

- mythril/Cargo.lock
- mythril/Cargo.toml
- mythril/src/acpi/fadt.rs
- mythril/src/acpi/madt.rs
- mythril/src/acpi/mod.rs
- mythril/src/acpi/rsdp.rs
- mythril/src/acpi/rsdt.rs
- mythril/src/acpi/seabios.rs
- mythril/src/error.rs
- mythril/src/kmain.rs
Build the RSDP and pass it to the guest via the seabios table-loader feature.
We also now fill out the MADT with a implementation of the `SDTBuilder`
trait and the `MADTBuilder`
As seen below, we do indeed control the RSDP and the Interrupt Control
Address (in this case a bad address).
```
GUEST0: Copying ACPI RSDP from 0x40000008 to 0x000f4ca0
GUEST1: Copying ACPI RSDP from 0x40000008 to 0x000f4ca0
...
GUEST0: [    0.000000][    T0] ACPI: RSDP 0x00000000000F4CA0 000024 (v02       )
GUEST1: [    0.000000][    T0] ACPI: RSDP 0x00000000000F4CA0 000024 (v02       )
GUEST0: [    0.000000][    T0] ACPI: XSDT 0x0000000040001000 00002C (v01                 00000000      00000000)
GUEST1: [    0.000000][    T0] ACPI: XSDT 0x0000000040001000 00002C (v01                 00000000      00000000) …
```
> acpi: build the RSDP and pass it to the guest

- .gitignore
- mythril/src/memory.rs
- mythril/src/vm.rs
Fixes: #77 
Uses already defined constants from the x86 crate in memory.rs, which is already very x86-specific.
Uses size_of() an already defined type in vm.rs to avoid adding an x86 dependency.
> Replace magic page size numbers with constants

- mythril/src/emulate/cpuid.rs
- mythril/src/kmain.rs
- mythril/src/memory.rs
- mythril/src/vcpu.rs
- mythril/src/virtdev/ioapic.rs
- mythril/src/virtdev/lapic.rs
- mythril/src/virtdev/mod.rs
- mythril/src/vm.rs
- mythril/src/vmexit.rs
- scripts/mythril.cfg
This starts to add support for guest apic interaction (which is necessary for multi core guest support). The initial steps here are as follows:
- Setup a guest APIC access page (this is shared by all cores, it is just the target page that is mapped by EPT for the local apic address range)
- For now, ignore all APIC access vm exits, just like we currently ignore PIC writes
- Move the local apic to being per-core
- Add an IoApic type that is a normal memory mapped device (though it currently doesn't do anything)
> Add support for guest booting with APIC enabled
